# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: %%CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE%%
  licenses: Apache-2.0
apiVersion: v2
appVersion: %%UPSTREAM_PROJECT_VERSION%%
dependencies:
  - condition: SUBCHART_NAME.enabled
    name: SUBCHART_NAME
    repository: oci://registry-1.docker.io/bitnamicharts
    version: %%MAJOR_SUBCHART_VERSION_(A.X.X)%%
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: %%DESCRIPTION%%
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: %%CHART_NAME%%
version: 0.1.0
